-- DESIGN DECISION: Custom ENUM for 'origin'
-- Why: This strictly enforces the "Action" logic required in the brief. 
-- It prevents data corruption and ensures that the analytics for 
-- "AI vs Agent" performance are 100% accurate.
CREATE TYPE message_origin AS ENUM (
    'ai_drafted',   -- Message generated by Claude but not yet sent
    'agent_edited',  -- AI draft that was modified by a human before dispatch
    'auto_sent',     -- Dispatched by the system (High confidence score > 0.85)
    'manual_agent',  -- Sent by a human without AI assistance
    'inbound'        -- Received from the guest via webhook
);

-- DESIGN DECISION: UUIDs over Serial Integers
-- Why: UUIDs provide better security (ids cannot be guessed) and 
-- easier data merging if Nistula scales to multiple regional databases.
-- Plus, it avoids the leaky abstraction of showing how many guests we have.
CREATE TABLE guests (
    guest_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    full_name VARCHAR(255) NOT NULL, -- Unified name from webhook 'guest_name'
    email VARCHAR(255) UNIQUE,       -- Ensures a single profile across channels
    phone_number VARCHAR(20) UNIQUE, -- Primary key for WhatsApp identity
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- DESIGN DECISION: The Reservation-Property Link
-- Why: Linking 'property_id' here allows the system to inject the correct
-- villa-specific context (e.g., Villa B1 vs Villa A2) into the AI prompt.
CREATE TABLE reservations (
    reservation_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    guest_id UUID NOT NULL REFERENCES guests(guest_id) ON DELETE CASCADE,
    booking_ref VARCHAR(50) UNIQUE NOT NULL, -- Matches webhook 'booking_ref'
    property_id VARCHAR(50) NOT NULL,        -- e.g., 'villa-b1'
    check_in TIMESTAMP WITH TIME ZONE,
    check_out TIMESTAMP WITH TIME ZONE,
    status VARCHAR(50) DEFAULT 'confirmed',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- DESIGN DECISION: Conversations as Logical "Containers"
-- Why: A guest might chat via WhatsApp and then switch to Email.
-- Using a conversation table allows us to group messages by channel 
-- and stay/reservation, rather than having one giant mess of messages.
CREATE TABLE conversations (
    conversation_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    guest_id UUID NOT NULL REFERENCES guests(guest_id),
    reservation_id UUID REFERENCES reservations(reservation_id), -- Nullable for pre-sales
    channel VARCHAR(20) NOT NULL,           -- 'whatsapp', 'airbnb', 'direct', etc.
    is_active BOOLEAN DEFAULT true,
    last_message_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- DESIGN DECISION: Unified Message Table with AI Metadata
-- Why: Storing confidence and query_type here allows Nistula to track 
-- AI accuracy over time. 'TEXT' type for content avoids character limits.
-- Note: 'external_timestamp' is key for re-ordering messages if the API is slow.
CREATE TABLE messages (
    message_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id UUID NOT NULL REFERENCES conversations(conversation_id),
    direction VARCHAR(10) CHECK (direction IN ('inbound', 'outbound')),
    content TEXT NOT NULL,
    origin message_origin NOT NULL,         -- Driven by the ENUM defined above
    query_type VARCHAR(100),                -- e.g., 'pre_sales_availability'
    confidence_score DECIMAL(5, 4),         -- Store up to 4 decimal places for precision
    external_timestamp TIMESTAMP WITH TIME ZONE, -- The 'timestamp' from original webhook
    agent_id UUID,                          -- Tracks which human edited the draft
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- PERFORMANCE: Indexes
-- Why: These are critical for an "Inbox" view. We must be able to load 
-- all messages for a conversation instantly without a sequential scan.
-- This keeps the UI snappy even as the DB grows.
CREATE INDEX idx_messages_conversation ON messages(conversation_id);
CREATE INDEX idx_reservations_guest ON reservations(guest_id);

/*
--------------------------------------------------------------------------------
THE HARDEST DESIGN DECISION:
The toughest call was deciding whether 'reservation_id' should be mandatory 
or optional in the 'conversations' table. In hospitality, it's easy to assume 
every chat is about an existing booking. But Nistula's brief includes 'pre_sales' 
stuff—meaning people asking questions before they buy. If I made the reservation 
link mandatory, we'd lose every single potential lead because the DB would 
reject them. I chose to keep it nullable (optional). It lets the system capture 
lead data immediately, creating a 'Guest' record and 'Conversation' way before 
a 'Reservation' even exists. It’s better to have a slightly looser schema than 
to reject real customer inquiries because of a missing ID.
--------------------------------------------------------------------------------
*/